name: Build & Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Optional Tag'
        required: false

jobs:
  container-job:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: golang:1.17

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: secret
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out
        uses: actions/checkout@v2
#      - name: Build
#        run: make build
      - name: Test
        run: make test
        env:
          OME_REDIS_STORE_HOST: redis:6379
          OME_REDIS_PUBSUB_HOST: redis:6379