name: Build & Test

on:
  pull_request: # Apply to all pull requests
  push:
    branches:
      - main # Apply to all pushes to `main`
  workflow_dispatch:
    inputs:
      tags:
        description: 'Optional Tag'
        required: false

jobs:
  container-job:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: golang:1.17

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: ome
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test
        env:
          OME_REDIS_STORE_ADDR: redis:6379
          OME_REDIS_PUBSUB_ADDR: redis:6379
          OME_PGDB_ADDR: postgres://postgres:secret@postgres:5432/ome

      # Check to see if there were any protobuf changes
      - name: Check for protobuf changes
        uses: technote-space/get-diff-action@v6
        id: git-diff
        with:
          PATTERNS: |
            api/**/*

      # Get JWT for our GitHub App.
      # This will be used only for the repository_dispatch in the next step.
      - name: Get GitHub App JWT
        # Only execute if there were any protobuf changes
        if: steps.git-diff.outputs.diff
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      # Trigger build in another GitHub repo using repository_dispatch
      - name: Dispatch event to self to trigger build of protobufs
        # Only execute if there were any protobuf changes
        if: steps.git-diff.outputs.diff
        env:
          ACCESS_TOKEN: ${{ steps.get_token.outputs.app_token }}
        run: |
          curl -X POST https://api.github.com/repos/openmarketplaceengine/openmarketplaceengine/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            --data '{"event_type": "build_protobufs", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'