name: Build & Test

on:
  push:
    branches:
      - main
      - 'feat/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Optional Tag'
        required: false

jobs:
  container-job:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: golang:1.17

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: ome
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
      - uses: bufbuild/buf-lint-action@v1
      - uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test
        env:
          OME_REDIS_STORE_ADDR: redis:6379
          OME_REDIS_PUBSUB_ADDR: redis:6379
          OME_PGDB_ADDR: postgres://postgres:secret@postgres:5432/ome

  publish-protos:
    # Only publish protos on main branch
    if: ${{ github.ref == 'refs/heads/main' }}
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The environment we want to access.
    # If no environment is specified, Github environment secrets will be 
    # silently inaccessible.
    # TODO I'm not sure we need to specify an environment if protobus are
    #  env-agnostic.
    environment: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1

      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: .

      - name: Dispatch event to trigger build of TypeScript protobufs
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/openmarketplaceengine/ome-proto-ts/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -u openmarketplaceengine:${{ secrets.GITHUB_TOKEN }} \
            --data '{"event_type": "build", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'