name: Publish protobufs

on:
  push:
    paths:
      - 'omeapi/**/*'
  # Only run this workflow after the code has been built and tested.
  repository_dispatch:
    types: [build_protobufs]

jobs:
  publish-protos:
    # Job only runs on main branch
    if: ${{ github.ref == 'refs/heads/main' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1

      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: .

      # Get JWT for our GitHub App.
      - name: Get GitHub App JWT
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      # Trigger build in another GitHub repo
      - name: Dispatch event to trigger build of TypeScript protobufs
        env:
          ACCESS_TOKEN: ${{ steps.get_token.outputs.app_token }}
        run: |
          curl -X POST https://api.github.com/repos/openmarketplaceengine/ome-proto-ts/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            --data '{"event_type": "build_upstream_proto_repo", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'